<?php
declare(strict_types=1);
require_once __DIR__ . '/database.php';
const CUSTOMER_PROFILE_FIELDS=['first_name','last_name','username','phone','country','email','city','address','tax_id','details','wa_id','wa_profile_name'];
function getCustomers(int $limit=CUSTOMERS_PAGE_SIZE,int $offset=0,string $search=''):array{$rows=Supabase::client()->rpc('get_customers_with_preview',['p_search'=>$search,'p_limit'=>$limit+1,'p_offset'=>$offset]);$more=count($rows)>$limit;if($more)array_pop($rows);foreach($rows as &$r)unset($r['total_count'],$r['last_activity_id']);return['rows'=>$rows,'hasMore'=>$more];}
function getCustomer(string $id):?array{return Supabase::client()->get('livar_customer',['session_id'=>'eq.'.$id,'select'=>'*','limit'=>'1'])['rows'][0]??null;}
function getCustomerByWaId(string $id):?array{$id=preg_replace('/\D+/','',$id)??'';return Supabase::client()->get('livar_customer',['wa_id'=>'eq.'.$id,'select'=>'*','limit'=>'1'])['rows'][0]??null;}
function createCustomer(array $d):array{$p=['session_id'=>$d['session_id']??generate_session_id()];foreach(CUSTOMER_PROFILE_FIELDS as $f)$p[$f]=($d[$f]??'')===''?null:$d[$f];return Supabase::client()->post('livar_customer',$p)[0]??$p;}
function updateCustomer(string $id,array $d):?array{$p=[];foreach(CUSTOMER_PROFILE_FIELDS as $f)if(array_key_exists($f,$d))$p[$f]=$d[$f]===''?null:$d[$f];if(!$p)return getCustomer($id);return Supabase::client()->patch('livar_customer',['session_id'=>'eq.'.$id],$p)[0]??null;}
function getOrCreateCustomerByWaId(string $id,string $name=''):array{$id=preg_replace('/\D+/','',$id)??'';if($id==='')throw new InvalidArgumentException('Invalid WhatsApp id');$old=getCustomerByWaId($id);if($old)return $old;$p=['session_id'=>'wa_'.$id,'wa_id'=>$id,'phone'=>$id,'wa_profile_name'=>$name?:null,'first_name'=>$name?:null];return Supabase::client()->upsert('livar_customer',$p,'wa_id')[0]??$p;}
function touchLastInbound(string $id):void{Supabase::client()->patch('livar_customer',['session_id'=>'eq.'.$id],['last_inbound_at'=>gmdate('c')]);}
function insertWhatsAppMessage(string $id,array $f):?array{$content=(string)($f['content']??'');$p=array_merge($f,['session_id'=>$id,'message'=>['type'=>($f['direction']??'in')==='out'?'ai':'human','content'=>$content],'msg_type'=>$f['msg_type']??'text']);unset($p['content']);try{return Supabase::client()->post('n8n_chat_history',$p)[0]??$p;}catch(SupabaseException $e){if($e->httpStatus===409&&!empty($f['wa_message_id']))return null;throw $e;}}
function updateMessageStatus(string $id,string $status,string $error=''):void{Supabase::client()->patch('n8n_chat_history',['wa_message_id'=>'eq.'.$id],['wa_status'=>$status,'wa_error'=>$error?:null]);}
function setMessageMedia(int $id,string $path,string $mime,int $size):void{Supabase::client()->patch('n8n_chat_history',['id'=>'eq.'.$id],['media_path'=>$path,'media_mime'=>$mime,'media_size'=>$size]);}
function getMessageRow(int $id):?array{return Supabase::client()->get('n8n_chat_history',['id'=>'eq.'.max(0,$id),'select'=>'*','limit'=>'1'])['rows'][0]??null;}
function getMessages(string $id,int $since=0,int $limit=200):array{$rows=Supabase::client()->get('n8n_chat_history',['session_id'=>'eq.'.$id,'id'=>'gt.'.max(0,$since),'select'=>'*','order'=>'id.asc','limit'=>(string)$limit])['rows'];$out=[];foreach($rows as $r){$m=is_string($r['message'])?json_decode($r['message'],true):$r['message'];if(!is_array($m)||!isset($m['type']))continue;$out[]=['id'=>(int)$r['id'],'type'=>$m['type'],'content'=>$m['content']??'','created_at'=>$r['created_at']??null,'direction'=>$r['direction']??null,'msg_type'=>$r['msg_type']??'text','media_url'=>(!empty($r['media_path'])||!empty($r['wa_media_id']))?'api/media.php?id='.(int)$r['id']:null,'media_mime'=>$r['media_mime']??null,'media_size'=>$r['media_size']??null,'media_name'=>$r['media_name']??null,'latitude'=>$r['latitude']??null,'longitude'=>$r['longitude']??null,'place_name'=>$r['place_name']??null,'place_address'=>$r['place_address']??null,'wa_status'=>$r['wa_status']??null];}return$out;}
function isWithin24hWindow(?string $at):bool{$t=$at?strtotime($at):false;return$t!==false&&$t>=time()-86400;}

