<?php
declare(strict_types=1);
require_once __DIR__.'/load_config.php';
final class WhatsAppException extends RuntimeException{public function __construct(string $message,public readonly int $httpStatus=500){parent::__construct($message);}}
final class WhatsApp{
 private static ?self $instance=null;private const BASE='https://waba-v2.360dialog.io';private function __construct(){if(!defined('D360_API_KEY')||D360_API_KEY===''||str_starts_with(D360_API_KEY,'REPLACE_'))throw new WhatsAppException('WhatsApp is not configured.',500);}public static function client():self{return self::$instance??=new self();}
 public function sendText(string $to,string $body):array{return$this->json('POST','/messages',['messaging_product'=>'whatsapp','to'=>$to,'type'=>'text','text'=>['body'=>$body,'preview_url'=>true]]);}
 public function sendMedia(string $to,string $type,string $id,string $caption='',string $filename=''):array{$media=['id'=>$id];if($caption!=='')$media['caption']=$caption;if($filename!==''&&$type==='document')$media['filename']=$filename;return$this->json('POST','/messages',['messaging_product'=>'whatsapp','to'=>$to,'type'=>$type,$type=>$media]);}
 public function sendLocation(string $to,float $lat,float $lng,string $name='',string $address=''):array{return$this->json('POST','/messages',['messaging_product'=>'whatsapp','to'=>$to,'type'=>'location','location'=>array_filter(['latitude'=>$lat,'longitude'=>$lng,'name'=>$name,'address'=>$address],fn($v)=>$v!=='' )]);}
 public function uploadMedia(string $path,string $mime):string{$ch=curl_init(self::BASE.'/media');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>['messaging_product'=>'whatsapp','file'=>new CURLFile($path,$mime,basename($path))],CURLOPT_HTTPHEADER=>['D360-API-KEY: '.D360_API_KEY],CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>60]);$body=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);$d=json_decode((string)$body,true);if($err||$status>=300||empty($d['id']))$this->fail($status,(string)$body,$err);return(string)$d['id'];}
 public function fetchMedia(string $id):array{$meta=$this->json('GET','/'.rawurlencode($id));$url=(string)($meta['url']??'');if($url==='')throw new WhatsAppException('Media URL missing.',502);$u=parse_url($url);$u['host']='waba-v2.360dialog.io';$url='https://'.$u['host'].($u['path']??'').(isset($u['query'])?'?'.$u['query']:'');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_HTTPHEADER=>['D360-API-KEY: '.D360_API_KEY],CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>60]);$bytes=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);$mime=curl_getinfo($ch,CURLINFO_CONTENT_TYPE)?:($meta['mime_type']??'application/octet-stream');$err=curl_error($ch);curl_close($ch);if($err||$status>=300)$this->fail($status,(string)$bytes,$err);$size=strlen((string)$bytes);if($size>(defined('WHATSAPP_MAX_MEDIA_BYTES')?WHATSAPP_MAX_MEDIA_BYTES:16777216))throw new WhatsAppException('Media is too large.',413);return['bytes'=>(string)$bytes,'mime'=>(string)$mime,'size'=>$size];}
 private function json(string $method,string $path,?array $data=null):array{$ch=curl_init(self::BASE.$path);$opts=[CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>['D360-API-KEY: '.D360_API_KEY,'Content-Type: application/json'],CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>45];if($data!==null)$opts[CURLOPT_POSTFIELDS]=json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);curl_setopt_array($ch,$opts);$body=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);$decoded=json_decode((string)$body,true);if($err||$status>=300||!is_array($decoded))$this->fail($status,(string)$body,$err);return$decoded;}
 private function fail(int $status,string $body,string $err=''):never{error_log("[WhatsApp] HTTP $status $err: $body");$d=json_decode($body,true);$msg=$d['error']['message']??$d['meta']['developer_message']??'WhatsApp request failed.';throw new WhatsAppException((string)$msg,$status>=400&&$status<600?$status:502);}
}
function saveWhatsAppMedia(array $media):array{$map=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','video/mp4'=>'mp4','audio/ogg'=>'ogg','audio/mpeg'=>'mp3','application/pdf'=>'pdf'];$mime=strtolower(trim(explode(';',(string)$media['mime'])[0]));$ext=$map[$mime]??'bin';$rel='media/'.gmdate('Y/m').'/'.bin2hex(random_bytes(16)).'.'.$ext;$abs=dirname(__DIR__).'/storage/'.$rel;if(!is_dir(dirname($abs))&&!mkdir(dirname($abs),0750,true)&&!is_dir(dirname($abs)))throw new RuntimeException('Cannot create media directory');if(file_put_contents($abs,$media['bytes'],LOCK_EX)===false)throw new RuntimeException('Cannot save media');return['path'=>$rel,'absolute'=>$abs,'mime'=>$mime,'size'=>(int)$media['size']];}

